name: universal_html
version: 1.2.4
description:
  A 'dart:html' that works in all platforms, including Flutter and server-side.
  Eases cross-platform development and other HTML / XML processing.
homepage: https://github.com/dint-dev/universal_html

environment:
  sdk: '>=2.8.0 <3.0.0'

dependencies:
  async: ^2.4.0
  charcode: ^1.1.0
  collection: ^1.14.0
  csslib: ^0.16.0
  html: ^0.14.0
  meta: ^1.2.0
  typed_data: ^1.2.0
  universal_io: '>=1.0.2 <3.0.0'
  zone_local: '>=0.1.0 <0.3.0'

dev_dependencies:
  pedantic: ^1.9.2
  stream_channel: ^2.0.0
  test: ^1.15.7