name: universal_html
version: 2.3.0
description:
  A 'dart:html' that works in all platforms, including Flutter and server-side.
  Eases cross-platform development and HTML / XML processing.
homepage: https://github.com/dint-dev/universal_html

environment:
  sdk: ^3.6.0

dependencies:
  async: ^2.11.0
  csslib: ^1.0.2
  charcode: ^1.2.0
  collection: ^1.17.1
  html: ^0.15.3
  meta: ^1.9.1
  source_span: ^1.9.1
  typed_data: ^1.3.2
  universal_io: ^2.3.1

dev_dependencies:
  lints: '>=3.0.0 <7.0.0'
  stream_channel: ^2.1.1
  test: ^1.24.3