name: universal_html
version: 0.0.1
description: Supports a subset of 'dart:html' in all platforms (browser, VM, and Flutter).
homepage: https://github.com/terrier989/dart-universal_html
author: terrier989 <terrier989@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  charcode: ^1.1.2
  csslib: ^0.14.5
  html: ^0.13.3
  meta: ^1.1.6

dev_dependencies:
  test: ^1.3.0