name: universal_html_flutter_test
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  universal_html:
    path: '..'

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^6.0.0
  stream_channel:
  test: